<?php

require_once 'setup.php';

$corona = true;
$coronaJohannespassion = true;

//$titelbild= array('/img/_MG_0656_st nikolai panoAnd6more_tonemapped.jpg', true);

ob_start() ?>

# Gottesdienst-Reihe zur Johannes-Passion von J.S. Bach

<hr style="margin-top: 2em;">

## „Jesus Christus – wahrer Gott“
### Der Passionsbericht nach Johannes<br>Pastorin Maren Schmidt, März 2020
<p style="margin-top: 0;" class="klappinfo_open klappinfo_right"><a href="#" class="klappinfo_open" data-id="text1">&#9661; Mehr Informationen</a></p>

<div class="klappinfo" data-id="text1">
<p>Liebe Gemeinde,</p>
<p>„vermutlich“ ist wohl eines der häufigsten Worte der Theologie.</p>
<p>Da gab es also einen Schriftsteller und Theologen, der vermutlich Ende des ersten Jahrhunderts n.Chr. die Geschichte Jesu Christi aufschrieb. Möglicherweise hieß er Johannes, vermutlich war er aber kein Augenzeuge der Ereignisse, über die er berichtete. Manches weist darauf hin, dass er in Ephesus schrieb. Ob er die anderen Evangelien kannte – darüber streiten sich Theologen bis heute vortrefflich. Aber es lässt sich vermuten, dass ihm zumindest das Markusevangelium bekannt war.</p>
<p>Was sich aber mit Sicherheit sagen lässt, ist, dass wir mit dem Johannesevangelium ein inspirierendes Glaubenszeugnis in den Händen halten - literarische und theologische Kompositionskunst vom Feinsten. Johannes erzählt uns die Geschichte Jesu Christi - neu und anders als die anderen Evangelisten es tun.</p>
<p><em><b>Im Anfang war das Wort, und das Wort war bei Gott und das Wort war Gott.</b></em></p>
<p>Für Johannes beginnt diese Geschichte nicht mit einem Stammbaum Jesu, nicht mit einer Herbergssuche und Hirten – der Anfang der Geschichte liegt aller Zeit voraus.</p>
<p><em><b>In ihm war das Leben und das Leben war das Licht der Menschen. Und das Licht scheint in der Finsternis und die Finsternis hat´s nicht ergriffen. (…)</b></em></p>
<p><em><b>Und das Wort ward Fleisch und wohnte unter uns und wir schauten seine Herrlichkeit; eine Herrlichkeit als des eingeborenen Sohnes vom Vater, voller Gnade und Wahrheit.</b></em></p>
<p>Wie in einer Ouvertüre klingen in diesen ersten Zeilen des Evangeliums bereits die Themen und Motive an, die im Folgenden narrativ entfaltet werden: Der, von dem Johannes erzählen will, ist eines Wesens mit Gott und war es seit Anbeginn. Er ist das Licht und das Leben, aber die Welt erkennt ihn nicht.</p>
<p><em><b>Herr, unser Herrscher, dessen Ruhm in allen Landen herrlich ist.</b></em></p>
<p>Im Rückgriff auf Psalm 8 nimmt Johann Sebastian Bach diesen Ton auf und eröffnet seine musikalische Übersetzung der johanneischen Passion mit einem christologischen Bekenntnis, in dem Hoheit und Schöpfermacht Jesu Christi zum Klingen kommen.</p>
<p>Ließ er seine Matthäus-Passion mit einer Aufforderung zur Klage beginnen, ist der Auftakt der Johannes-Passion ein Hymnus - und in diesem Klang soll alles weitere gehört werden: Auch und gerade im erniedrigten und getöteten Jesus ist es Gott selbst, der handelt und seine Herrlichkeit offenbart:</p>
<p><em><b>Zeige uns durch deine Passion, dass du, der wahre Gottessohn, zu aller Zeit, auch in der größten Niedrigkeit, verherrlicht worden bist.</b></em></p>
<p>Das Johannes-Evangelium ist eine in Worte gefasste Bewegung, die Johann Sebastian Bach auf großartige Weise in Musik übersetzt hat: Wir werden aus der Höhe der göttlichen Herrlichkeit in die Tiefe des irdischen Daseins bis in die tiefste Tiefe der Erniedrigung am Kreuz geführt, die aber als Erhöhung und Rückkehr zum Vater gedeutet wird und unseren Blick wieder in die Höhe lenkt.</p>
<p>Es bleibt für Johannes die Herausforderung, diesen Gang Jesu in die tiefste Tiefe alles Menschlichen zur Darstellung zu bringen – wie kann der ewige Gottessohn sterben, sogar sterben „müssen“?</p>
<p>Johannes konzipiert und komponiert sein gesamtes Evangelium so, dass Leser und Leserinnen diesen Teil des Weges Jesu richtig verstehen und führt - anders als Mk – seine Erzählung von Beginn an in diese Richtung. Immer wieder streut er Hinweise auf „Jesu Stunde“ ein, die sukzessive immer deutlicher als die Stunde seines Todes erkennbar wird.</p>
<p>Und immer wieder lässt er Jesus selbst in meditativ-theologischen Reden andeuten und ausdeuten, woher er kommt und wohin sein Weg führen wird. Dieser Tod ist liebende Hingabe – für die Welt, für die Schafe, für die Freunde, für das Volk.</p>
<p><em><b>Denn so sehr hat Gott die Welt geliebt, dass er seinen eingeborenen Sohn gab, damit alle, die an ihn glauben, das ewige Leben haben.</b></em></p>
<p>Dem Evangelisten geht es nicht allein um die Darstellung der Herrlichkeit und Hoheit Jesu Christi, sondern um die glaubende Aneignung der Passion als ein Geschehen, das uns Menschen Heil und Erlösung bringt.</p>
<p>So baut Johannes mit dem Hohepriesterlichen Gebet – Auszüge haben wir in der Lesung gehört – eine literarische Brücke vom Leben und Wirken Jesu zur Passionserzählung, die uns zu Beteiligten des Geschehens macht.</p>
<p>Jesus betet zu seinem Vater für die Seinen, für die, die der Welt das Heil verkündigen werden und für alle, die diesen Glauben annehmen.</p>
<p>Die Leser*innen verbleiben nicht in der Haltung des Betrachtens und rechten Verstehens, sondern werden hineingeholt in die Liebe zwischen Vater und Sohn.</p>
<p><em><b>Wie du, Vater, in mir bist und ich in dir bin, sollen auch sie in uns sein. Ich habe ihnen deinen Namen kundgetan und werde ihn kundtun, damit die Liebe, mit der Du mich liebst, in ihnen sei und ich in ihnen.</b></em></p>
<p>Aneignung und Verinnerlichung des Glaubens - Johann Sebastian Bach hat einen musikalischen Ausdruck für dieses Anliegen des Evangelisten gefunden, der einen kaum unberührt lassen kann.</p>
<p><em><b>SanktNikolaiChor: Durch dein Gefängnis</b></em></p>
<p>Freiheit wird uns geschenkt, weil Jesus sich freiwillig in die Knechtschaft gab. Was Johannes in 17 Kapiteln vorbereitet hat, wird nun im Passionsbericht konkret:</p>
<p>Der Tod Jesu erfolgt in der von Gott bestimmten Stunde als Vollendung des göttlichen Willens. Dieser Wille ist in der Schrift vorgegeben und wird als Akt der liebenden Hingabe Gottes erkennbar.</p>
<p>Unter diesem Vorzeichen können Leiden und Sterben Jesu nicht das Ergebnis menschlicher Intrige oder ein Justizskandal sein. Johannes erzählt von einem Jesus, der sich wissend, freiwillig und mit königlicher Souveränität in den Tod begibt.</p>
<p>Dafür muss der Anspruch historischer Richtigkeit der theologisch-künstlerischen Freiheit weichen, in der Johannes von der Passion erzählt. Ihn treibt beim Schreiben nicht die Darstellung des vor aller Augen Geschehenen, sondern das Sichtbarmachen der Wahrheit, die hinter diesen Geschehnissen liegt.</p>
<p>So lässt er beispielsweise bei der Gefangennahme eine römische Kohorte von 600 Mann auftreten – historisch ist das ausgesprochen unwahrscheinlich. Aber er lässt vor unseren Augen ein mächtiges Bild entstehen:</p>
<p>Eine riesige Truppe aus Juden und Heiden – die ganze Welt tritt einem Unbewaffneten entgegen. Sie kommen mit Waffen, Fackeln und Laternen, um das Licht der Welt einzufangen.</p>
<p>Den Judaskuss braucht Johannes nicht, denn Jesus geht der Truppe selbst entgegen. Er gibt sich zu erkennen mit dem hoheitsvollen „Ich bin es.“ und spricht damit eben die Worte, mit denen Gott sich im Alten Testament selbst offenbart.</p>
<p>Die gigantische Truppe weicht zurück und stürzt. Ein unfreiwilliger Kniefall der ganzen Welt vor dem, der sich als der „Ich bin“ offenbart. Dramatischer hätte die göttliche Souveränität kaum zum Ausdruck kommen können.</p>
<p>Die Mitte der johanneischen Passionserzählung bildet der Prozess vor Pilatus. Was bei Markus in wenigen Sätzen erzählt ist, entfaltet Johannes dramaturgisch kunstvoll in sieben Szenen – und jede wäre einer eigenen Predigt wert.</p>
<p><em><b>Ach, großer König, groß zu allen Zeiten</em></b> lässt Bach wie ein Intermezzo inmitten des Verhörs singen – Ruhe und Majestät Jesu durchdringen diesen Prozess.</p>
<p>Wir werden Zeugen theologischer Gespräche zwischen Jesus und Pilatus, in denen es nicht um Schuld oder Unschuld geht, sondern um das Königtum Jesu, um seine wahre Herkunft und Identität. Durch kleine, aber sehr feine literarische Handgriffe, gerät Pilatus in eine fast schon passive Nebenrolle. Der Lenker des Geschehens, der wahre Richter – das ist Jesus.</p>
<p>Und en passant löst sich Johannes in dieser Passage auch von der chronologischen Einordnung der anderen Evangelisten. Während dort das letzte Abendmahl als Passahmahl gefeiert wurde, deutet Johannes hier an, dass das Passahmahl erst noch bevorsteht.</p>
<p>So wird Jesus im 4. Evangelium ungefähr zu der Zeit sterben, zu der im Tempel die Passah-Lämmer geschlachtet werden. Jesus wird zum wahren Passah-Lamm - so wie Johannes, der Täufer es bereits im ersten Kapitel bezeugt: Siehe, das ist Gottes Lamm, das der Welt Sünde trägt.</p>
<p>Signifikant ist schließlich das letzte Wort, das Johannes Jesus in den Mund legt: <b><em>Es ist vollbracht.</em></b></p>
<p>Gerade kein Aufschrei der Gottverlassenheit wie bei Markus, sondern Vollendung und Triumph. Nicht Entehrung, sondern Verherrlichung; nicht Erniedrigung, sondern Erhöhung - und zwar paradoxer Weise am Kreuz.</p>
<p>Er leugnet dabei nicht die harte Wirklichkeit des Todes Jesu und er mildert nicht das Leiden.</p>
<p>Und doch soll auch in dieser Sterbeszene die dahinter liegende Wahrheit zutage treten, die den Jüngern nach Ostern erschlossen wurde.</p>
<p>Wer um den Auferstandenen weiß und an ihn glaubt, der sieht in der physischen Erhöhung am Kreuz die Erhöhung zum Vater und die Einsetzung Jesu in seine Herrschaft. „Mein Knecht wird erhöht und sehr verherrlicht sein“ zitiert Johannes aus dem Buch Jesaja und deutet in diesem Licht Jesu Tod am Kreuz.</p>
<p>Johannes malt uns mit seinem Evangelium ein Bild des Glaubens, das von Ostern her entworfen ist. Vom ersten Wort an führt Johannes die Erzählung in diese Richtung - oder andersherum: alles, was Johannes zu sagen hat, bekommt seinen Sinn von der Auferstehung her. Die Herrlichkeit des Auferstanden überglänzt in diesem Evangelium bereits den irdischen Weg Jesu.</p>
<p>Wer das im Kreuz erkennen kann, wer Jesus annimmt als das Licht der Welt, als die Auferstehung und das Leben – der wird Anteil haben an dieser Auferstehung, dem wird das ewige Leben geschenkt.</p>
<p>So gibt es bei Bach zum Beschluss der Passion kein Weinen und Klagen um die Gebeine Jesu wie in seiner Matthäus-Passion, sondern er lässt sie wiederum hymnisch enden mit der Hoffnung auf Auferstehung und neues Leben für uns:</p>
<p><em><b>Als denn vom Tod erwecke mich, dass meine Augen sehen dich in aller Freud, o Gottessohn, mein Heiland und Gnadenthron! Herr Jesu Christ, erhöre mich, ich will dich preisen ewiglich</b></em></p>
<p><em><b>Amen</b></em></p>
</div>

## „Jesus Christus – wahrer Mensch“
### Dr. Walter Thomas Kanzow (Facharzt für Psychiatrie und Psychotherapie), März 2020
<p style="margin-top: 0;" class="klappinfo_open klappinfo_right"><a href="#" class="klappinfo_open" data-id="text2">&#9661; Mehr Informationen</a></p>

<div class="klappinfo" data-id="text2">
<p>
<u>I. Was ist „Wahrheit“</u><br>
„Was ist Wahrheit?“ So fragt Pilatus. „Was ist Wahrheit?“<br>
Im Johannes-Evangelium reagiert Pilatus mit dieser Frage nach der „Wahrheit“ auf Jesus, der sich mit den Worten erklärt hatte: „ Ich bin dazu geboren und in die Welt kommen, dass ich die Wahrheit zeugen soll.“ In der Zuspitzung der Passion erklärt sich Jesus: Er sei gekommen, von der Wahrheit zu zeugen. Die Wahrheit – das wissen wir - ist Gott vorbehalten. Jesus will von ihm, von Gott, Zeugnis ablegen. Und dies geschieht - wie an keiner anderen Stelle - in und mittels seiner Passion.<br>
Die Geschichte seiner Passion ist die große religiöse Erzählung des Christentums. Die Geburt Jesu, aber mehr noch sein Sterben sind die kirchlichen Eckpfeiler. Das Kreuz, das auch hier unseren Kirchenraum beherrscht, das Kreuz bindet die größten Fragen ein, die dem Menschen beantwortet werden möchten: die Fragen nach Leben und Tod, nach Lebenssinn, nach einem letzten Aufgehobensein. All diese Fragen bündeln sich unter der Überschrift „Auferstehung“. Sie fragen nach der „Wahrheit“, nach Gott.
</p>
<p>Der Alltag lehrt uns: Ohne Gott und ohne Kirchensteuer zu leben: das klappt recht gut. Aber die Vorstellung, zuletzt ohne kirchliches Geleit beerdigt zu werden, bereitet oftmals dem Lauen wie dem Atheisten Schwierigkeiten. Spürbar wird eine unausgesprochene Leere, wenn der Verstorbene in seinem Abschied nur auf seine weltliche Tüchtigkeit, auf sich und Seinesgleichen bezogen bleibt. Ohne ein Drittes als Bezugsgröße, ohne etwas Übergeordnetes fehlt etwas Bergendes. Es fehlt das, was die Passionsgeschichte und das Kreuz ansprechen: das Wagnis des eigenen Zeugnis.</p>
<p>Wenn wir bescheiden beginnen:<br>
Eine unumstößliche Gewissheit bei der Geburt eines Menschen ist die, dass er sterben wird. Dieses Sterbenmüssen signalisiert jedem Tag des Lebens: Du bist ein Sterblicher. Der Mensch lebt mit seiner Sterblichkeit. Sie verkörpert seine Begrenztheit. Begrenztheit klingt zuerst nicht lebensfroh. Aber sie macht froh. Erst mit dem wachsenden Annehmen dieser Grenzen im Rahmen des scheinbar Unendlichen kann ein Selbstbewusstsein, eine Lebensfreude, können Freiheit und Verantwortlichkeit groß und zum Vergnügen werden.<br>
Während eine Geburt – so auch die von Jesus zu Weihnachten - noch ein illusionsreiches Schweifen für die Zukunft erlaubt, zwingt die Passion mit Nacktheit und Dornenkrone zu den großen Fragen. Genommen sind die Hüllen: genommen damit das Gewand, das sich der Mensch in seinem irdischen Leben im Miteinander gewirkt hat: das Festgewand wie das Schlampige, das Ungepflegte wie das Sorgsame. Auch, welches Tischkleid er auflegt.</p>
<p>Diese Hüllen für das irdische Leben hatte Gott uns mit auf den Weg gegeben. Wenn Sie in dem Alten Testament weit zurückblättern, dann finden Sie im 1. Buch Mose (3.Kapitel. V 21) wie Gott persönlich vor der Vertreibung aus dem Paradies Adam und Eva ein Gewandt für den Lebensweg mitgibt. : <em>„Und Gott der HERR machte Adam und seinem Weibe Röcke von Fellen und kleidete sie..“</em> In der Passionsgeschichte ist dieses Lebensgewandt unbedeutend geworden. Es schwindet auch die Vorstellung einer güldenen Grabbeigabe für ein gemäßes Weiterleben. Nacktheit und Dornenkrone meißeln dem sozialen Existieren, unserem irdischen Leben ein Ende: die Zeit des Rockes aus Fell ist vorbei.</p>
<p><u>II. Die Botschaft der nicht einen, sondern der vier Passionsgeschichten.</u><br>
Pilatus fragt. „Was ist Wahrheit?“ Er fragt es, ohne eine klare Antwort zu erwarten. Aber nicht nur ihm sondern auch im Neuen Testament“ wird eine eindeutige Antwort schon formal verweigert. Formal: es ist schon die Form. Nicht einmal - und damit eindeutig-, sondern viermal parallel wird das Leben Jesu und in dessen Zentrum die Passion erzählt. 4 Evangelisten wurden ausgewählt - denn es gab weitere, die nicht kanonisiert wurden. Diese 4 Evangelisten halten eine Erinnerung fest, in deren Mittelpunkt Jesus Christus steht.</p>
<p>Es sind – natürlicherweise und gewollt - vier verschiedene Berichte. Jeder Ansatz einer einhelligen historischen Wahrheitssuche liefe dieser gewollten Vielfalt zuwider. Es geht nicht um eine, gar die eine wahre Lebensgeschichte. Jeder Biograf – und die Evangelisten sind Biografen - erzählt standortgebunden, erzählt aus seiner Zeit, aus seiner Sicht und damit relativ <em>(Koselleck)</em>. Dem Leser wird so verdeutlicht: Im Hinblick auf Gott ist ohnehin alles Menschenwerk singulär, denn die letzte verbindende Wahrheit verkörpert nur Gott.<br>
Wir dürfen für diese Vielfalt dankbar sein: denn mit ihr wird uns selbst die Erlaubnis, mehr noch: die Aufforderung angetragen, uns mit ihr als Ungewisses zu beschäftigen. Wir dürfen und wir können – als singuläre Wesen - nicht anders, als unterschiedliche Sympathien zu entwickeln. Mit den synoptischen Passionsgeschichten eröffnet sich uns das Tor zu einer Vielfalt von Antworten zu der Frage nach der Wahrheit – wie bei Pilatus. Die formale Vielfalt des Neuen Testaments nimmt dem Inhalt das Diktat. Das Verlangen nach der einen Wahrheit verbietet sich: Das Wesentliche ist die Suche selbst. <em>(Nach Hannah Ahrendt)</em>. Der zweifelnde, der suchende <b>Mensch ist der „wahre Mensch“</b></p>
<p>Wir sollen bei dieser Suche Jesus nicht als Gott, sondern – wie Johannes ihm in den Mund legt – als den sehen, der von Gott Zeugnis ablegt. Gott selbst bleibt der Unverfügbare. Sähen wir Jesus als Gott und nicht als sein Mittler, ließen wir das mutige Suchen. Wir verfehlten den Gehalt der Passion und des Kreuzes. Sähen wir schon Jesus als Gott und maßten uns an, in ihm Gott zu erkennen und uns auf ihn zu berufen, blieben wir mit einer kurzsichtigen Zweiteilung in Gut und Böse in einem Aberglauben stecken. Der Aberglaube, Gott erkannt zu haben, hat – so möchte ich meinen - die christlichen Kirchen immer wieder zu Racheprogromen im Namen Christi veranlasst- Racheprogromen, in denen mit Überzeugung und Hass das Kreuz gegen Judas, Hohepriester und Juden geschwungen wurde. Aber Jesus Christus ist nicht Gott, sondern der, der auf Gott verweisen will.</p>
<p>Der Evangelist Johannes bekräftigt diese Rolle als Mittler, wenn er Pilatus über Jesus sagen lässt: <em>(„ecce homo“)</em> „Seht, der Mensch.“</p>
<p><u>III. Die Divergenz</u><br>
Die Evangelien nun müssen unterschiedlich sein: sie wurden 1-2 Generationen nach dem Tod Christi geschrieben, sie fußen nur z. T. auf gleichem Material – aber v. a.: Biografen sind verschiedene Menschen mit ihrem immer singulären Blickwinkel.<br>
Johannes weicht am meisten von den anderen ab. Er schildert Jesus bei aller Leidensgeschichte durchgehend hoheitsvoller, zeichnet ihn getragen in einer Gewissheit der göttlichen Sendung. Es gibt in seiner Lesart nicht den Konflikt mit Gott bei dem Gebet auf Gethsemane (bei Mt 27,46): „Mein Gott, mein Gott, warum hast Du mich verlassen?“). Und gegenüber Pilatus kehrt Jesus letztlich die Rolle des Richters um. Und auch der schändliche Kreuzestod wird überformt zu einem Akt des Heilsgeschehens und endet mit Jesu letztem Wort „Es ist vollbracht.“ (Joh 17,31).</p>
<p>Anders bei dem Evangelisten Matthäus: Bei ihm bestimmt das menschlich anrührende Leiden die Passionsgeschichte: nicht der gewisse, sondern der leidende, der zweifelnde, der verlassene Jesus teilt sich uns mit. Hin- und hergerissen hat er in seiner Doppelexistenz für Zweierlei Zeugnis zu sein: für die Erwartung des quälenden menschlichen Todes und der Auferstehung als Zeichen des Gottbezuges. Er weiß sich gottgesandt, er weiß von dem Verrat und den Bruderkuss des Judas, er sieht die Verleugnung und Einsamkeit voraus. Trotz all dieses Wissens quält ihn zuletzt der Zweifel an seiner göttlichen Bestimmung: „Mein Gott, mein Gott, warum hast Du mich verlassen?“ (Mt 27,46).</p>
<p><u>IV. Das wechselseitige Gefüge der Gestalten</u><br>
So wie die Evangelisten mit ihrem Blick auf Jesus voneinander abweichen, so muss auch ihr Blick auf die anderen Gestalten um Jesus herum unterschiedlich ausfallen. Im Johannes-Evangelium bedingt die von der Gewissheit als Gottessohn getragene Haltung Jesu, dass Pilatus seinerseits als der erscheint, über den gerichtet wird und sich zuletzt beugt. Pilatus ist nach seinem Hin und Her derjenige, der über dem Haupt Jesu an das Kreuz schreibt: „Jesus aus Nazareth, der Juden König“. Gegen den Einwand der Hohen Priester, dass Jesus nicht König „ ist“, sondern nur behaupte „es zu sein“, beharrt Pilatus auf dem Geschriebenen. Aber dieser Pilatus, der nach der unbeantwortbaren „Wahrheit“ gefragt hat, bewegt sich weiterhin spürbar im Ungewissen. Nichtsdestotrotz bleibt er beharrlich: „Geschrieben ist geschrieben.“ Den Jüngern gilt Jesu Fürsorge. Und Judas? Judas wird zum Gegenteil der Gottesgewissheit Jesu: In Judas sei der Satan gefahren, und nicht nur das: Johannes lastet ihm zudem an, dass er schon zuvor als Zahlmeister die Jünger betrogen habe.</p>
<p>Dagegen bei Matthäus: Das Feld um den zweifelnden, den einsamen Jesus ist ganz anders bestellt. Der Bruderkuss durch Judas bei der Übergabe besiegelt beider Schicksal. Jesus wusste von diesem Verratsgeschehen: er wusste, was geschehen würde, ohne sich und auch ohne Judas zu retten.</p>
<p>Beide sterben. Judas als die Gestalt, die als Werkzeug Gottes handelt, seine Schuld nicht rückgängig machen kann und ohne Glauben an eine Erlösung bleibt: Judas richtet sich - ganz Mensch. Auch die Jünger bleiben wie ungelenke Menschen hinter den Ereignissen unverständig zurück: sie haben Jesus nicht begriffen: Sie ziehen das Schwert, sie verleugnen ihn oder sie schlafen. So wie sie dumpf zurückbleiben, wächst die menschliche und glaubensbezogene Gestalt Jesu ins Einsame.</p>
<p>Und Pilatus im Matthäus-Evangelium? Im Gegensatz zu den Jüngern ist er zur Auseinandersetzung mit Jesus gezwungen. Er muss sich mit ihm befassen, weil er richten muss. Pilatus verkörpert die Unsicherheit: schon wie er hinein und wieder herausgeht, wie er Rat bei seiner Frau sucht, wie er sich die „Hände in Unschuld“ wäscht und doch vergeblich weil er ohne erkennbare “Gerechtigkeit“ mit seinem Spruch schuldig wird. Pilatus verkörpert die unbeantwortbare Frage nach der Wahrheit und m.E. die Schwierigkeit des Glaubens.</p>
<p>Diese skizzierten Rollen der Menschen um Jesus herum beziehen sich auf ihn und wie sie zu ihm stehen. Und jeder Evangelist prägt - vor einem gemeinsamen historischen Hintergrund - diese Rollen als seine eigene Komposition.</p>
<p><u>V. Der Autor als der Herr all seiner Figuren.</u><br>
Ein Autor – und so auch der jeweilige Evangelist - ist der Vater aller seiner Figuren. In seinen Figuren gestaltet, ja personifiziert ein Autor – in seiner <em>auctoritas</em> bewusst und unbewusst - seine gefühlten und ihm fassbaren Konflikte und Auseinandersetzungen. In seinen Schöpfungen und ihrem Handeln untereinander verdichtet er das einzelmenschliche Drama der Glaubensaussage; der Glaubensaussage, die sich zum Thema „Tod und Auferstehung“ stellt. Angesichts des unausweichlichen Kreuzestodes steht sie vor einem ohne jede rückwärtige Versicherung. Diese Frage nach der Bedeutung von „Tod und Auferstehung“ ist neben die des Pilatus gerückt: „Was ist Wahrheit?“</p>
<p>Auf diese durch die Evangelisten vierfach zementierte Herausforderung finden sich Reaktionen und damit mittelbar Antworten in ihren Gestaltungen: schauen Sie auf Pilatus, auf die Jünger, auf Judas oder auf die Hohepriester. Die jeweiligen menschlichen Antworten sind reichhaltig: Wütendes Verteidigen des Bestehenden; Verleugnen um des augenblicklichen Vorteils willen; Verschlafen; Verunsicherung; die Unerträglichkeit eigener Schuld.<br>Oder wenn wir auf Einzelne noch einmal genauer schauen: Pilatus z. B.: Konfrontiert mit Jesus ist er unsicher, denn der Rahmen seiner Praxis wird gesprengt, zu einem Urteil wird er getrieben, und zuletzt verteidigt er bei aller Unsicherheit trotzig seine Inschrift. Oder die Hohen Priester: Sie versuchen ihren traditionellen Glauben zu verteidigen. Sie wollen Glaubensabweichungen ausschalten, sie wollen Häresie und Ketzertum töten. Und das Volk: Wie bei jeder Demonstration bleibt in dem Geschrei das differenzierte Denken auf der Strecke.</p>
<p>Der Demonstrant opfert seine Vernunft einer Idee, die ihn selbst größer und bedeutender macht, gleichzeitig ihm eine persönlich vernünftige und vertretbare Auseinandersetzung erspart.</p>
<p>Bemerkt sei an dieser Stelle, dass die Passionsgeschichte nicht antisemitisch ist: sondern in dem Verhalten der Hohen Priester und des jüdischen Volkes die Auseinandersetzung der Orthodoxie mit einem neuen Denken in Szene gesetzt wird. Zu dieser Auseinandersetzung von Orthodoxie und Neuerung gehört immer der ewige Aufschrei des „Verrats“, des Verrats am Hergebrachten. Kurz bemerkt: Der tiefe Schmerz über den „Verrat“ ist das Unabdingbare der Wandlung.</p>
<p><em>(Sehr schön zu lesen bei Dostojewski in der „Legende vom Großinquisitor“. In der Zeit der Inquisition ist Jesus wieder auf Erden gekommen, tut Wunder, wird von dem Großinquisitor gefangengenommen. In dem Gefängniskeller macht der Großinquisitor in einem Monolog Vorwürfe: er störe die Ordnung. Er könnte ihn töten lassen. Und es endet mit dem Bild: „Nachdem der Inquisitor verstummt ist, wartet er eine Weile, was ihm sein Gefangener antworten werde. Dessen Schweigen bedrückt ihn. … Er möchte, dass Er ihm etwa sage, sei es auch etwas Bitteres und Furchtbares. Er aber nähert schweigend dem Greis und küsst ihn still auf seine blutleeren neunzigjährigen Lippen. Das ist seine ganze Antwort.“)</em></p>
<p><u>VI: Es soll unser inneres Drama werden: wir als unser eigener Autor.</u><br>
In der Passionsgeschichte ist eine aufregende Geschichte von Wandlung und Aufbruch. Sie ist nicht allein ein Drama, das die Evangelisten quasi historisch und als vergangen von Jesus Christus erzählen. Es ist auch nicht nur eine zugespitzte Geschichte menschlicher Reaktionen auf Jesus Christus mit seinem Verweis auf Gott. Und es ist auch nicht nur eine jeweils persönliche Verarbeitungsweise der Evangelisten, die sie angesichts der Passion und Auferstehung mit ihren Gestalten zu fassen suchen. Der Logos der Geschichte wartet nicht irgendwo in der historischen Peripherie. Der Logos bietet an zu lesen.<br>
Die Vielzahl der Evangelien bleibt für uns Einladung und Aufforderung, dass wir Jesus unsere Bedeutung verleihen sollen.<br>
Der Mensch kann nur im Miteinander existieren. Geleitet wird er immer von höheren Ideen: ob er Streit sucht, sich verliebt, Krieg führt oder sich versöhnt, ob er klaut oder kauft: er wird immer von etwas Drittem bestimmt. In all diesen mitmenschlichen Dimensionen seines Handelns geschieht ein innerer Dialog zu diesem Dritten. Das Dritte, das Übergeordnete, (die psychodynamisch „Triangulierung“) ist unser Versuch an der „Wahrheit“, der von der Passionsgeschichte her ausstrahlt.<br>
Glaube ist nicht Gewissheit: sondern (nach Augustinus) <em>das unruhig suchende Herz inmitten einer geheimnisvollen Welt.</em> Nicht die „Wahrheit“ ist ein Trost, sondern, dass der Mensch als zweifelnder Mensch „wahrer Mensch“ ist. Gäbe es die Wahrheit, dann schaffte sie auch die Pluralität der Evangelisten ab. Ihre Verschiedenheit gibt uns Freiheit. Auf die Erkenntnis „Wahrheit“ muss verzichtet werden, denn sie bleibt Gott zugeordnet.</p>
<p>Gott ist und bleibt der Unverfügbare. Jesus und seine Passion öffnen die größtmögliche Tür, es ist ein Tor, zu ihm als einladende Mittler.<br>
Wenn wir aber nach allen komplizierten Gedanken ganz weit zurückwandern und schließlich zu Sokrates gelangen, dann hören wir ihn den wahrhaft einfachen Satz sagen: <em>„Nachdenken macht frömmer.“</em></p>
</div>

## „Jesus Christus – wahrer Gott und wahrer Mensch“
### Das Triumphkruzifix in der St. Nikolai-Kirche in Kiel<br>Prof. Dr. Dr. h.c. Lars Olof Larsson (Prof. em. des Kunsthistorischen Instituts der CAU), März 2020
<p style="margin-top: 0;" class="klappinfo_open klappinfo_right"><a href="#" class="klappinfo_open" data-id="text3">&#9661; Mehr Informationen</a></p>

<div class="klappinfo" data-id="text3">
<p>Der Anblick des großen Triumphkreuzes in der Nikolaikirche ist uns wohl allen vertraut, und wir wissen natürlich auch, was es darstellt: Christus, ans Kreuz geschlagen, das Symbol schlechthin der christlichen Kirchen. Als solches hat es geradezu Zeichencharakter. Zeichen nimmt man zu Kenntnis, selten schenkt man ihnen aber seine Aufmerksamkeit. Viele Kruzifixe stellen auch kaum solche Ansprüche. Andere aber schon, und dazu gehört unser großes Triumphkruzifix. Es ist mehr als Zeichen und Symbol, es ist ein Bildwerk mit starker Individualität, vielschichtiger Aussage und einer mehr als 500-jährigen Geschichte. Schauen wir es also einmal etwas genauer an – und freuen wir uns darüber, dass es das Kruzifix noch gibt! Das ist nämlich alles andere als selbstverständlich. Wie durch ein Wunder überstand es den Bombenangriff auf die Kirche 1944, und wir können dankbar sein, dass die Reformation in Schleswig-Holstein, anders als in vielen anderen Gegenden von Deutschland, ohne Bildersturm von statten ging. Die Reformatoren waren unter Berufung auf das erste Gebot im Prinzip bilderfeindlich. Luthers Wittenberger Kollege Andreas von Karlstadt schreibt z.B.:</p>
<p>“Christi Reich ist ein Hörreich, nicht ein Sehe Reich [... ] denn die Augen führen nicht dahin, da wir Christum finden, sondern die Ohren müssen das thun!“</p>
<p>Daraus konnte eine absolute Ablehnung von Bildwerken in der Kirche und das Recht, sie mutwillig zu zerstören, abgeleitet werden. Dass es hier keinen Bildersturm gab, also keine gewaltsame Säuberung der Kirchen, verdanken wir der Kirchenordnung Johannes Bugenhagens. Bugenhagen stand Luther nahe und verhielt sich, wie dieser, der Bilderfrage eher gleichgültig gegenüber. Als „Merkbilder“, als Gedächtnisstützen, konnten Bilder mit biblischen Motiven toleriert werden. Missliebige Bildwerke wurden aber selbstvetrständlich aus den Kirchen entfernt. Von dem einst reichen Schatz an Heiligenbildern und anderen Bildwerken, den die Nikolaikirche vor der Reformation sicher beherbergte, ist fast nur das Triumphkruzifix erhalten geblieben.</p>
<p>Das Triumphkruzifix beeindruckt schon durch seine Größe. Das Kreuz misst über 5 m, die Christusgestalt etwa 2,5 m. Diese ist aus Holz (vermutlich Eichenholz) geschnitzt und farbig gefasst. Geschaffen wurde es von einem heute nicht mehr bekannten Bildschnitzer und einem ebenfalls unbekannten Fassmaler, vielleicht in Lübeck, um 1490.</p>
<p>Wie im Spätmittelalter üblich, ist Christus mit drei Nägeln ans Kreuz geschlagen worden. Sein Haupt, mit der schweren Dornenkrone gekrönt, ist zur Seite geneigt und die Augen geschlossen als Zeichen dafür, dass er tot ist.</p>
<p>Das Kruzifix hatte ursprünglich, wie heute, seinen Platz unter dem Gewölbebogen zwischen Chor und Langhaus. Diese waren durch eine Chorschranke getrennt. Bei der Restaurierung der Kirche 1877 wurde das Gitter entfernt und das Kruzifix über dem Altar angebracht. Auf seinen ursprünglichen Platz unter dem Triumphbogen kehrte es beim Wiederaufbau der Kirche nach dem Zweiten Weltkrieg zurück.</p>
<p>Ein Werk von dieser Größe und Qualität ausführen zu lassen war auch vor 500 Jahren sehr kostspielig. Die Stifter müssen sich also wesentliche Vorteile davon versprochen haben. In nachreformatorischer Zeit wurden Stiftungen, wie etwa Kanzeln, aber auch private Denkmäler wie Epitaphien, oft mit dem Spruch versehen: <em>Gott zu Ehren, der Kirche zur Zierde und der Stifterin/dem Stifter zum Gedächtnis.</em> Diese dreifache Motivation hatte sicher auch vor der Reformation ihre Gültigkeit. Wichtiger war damals wohl allerdings die Überzeugung, dass gute Taten heilsbringend seien – und eine grossartige Stiftung dieser Art war selbstverständlich eine gute Tat.</p>
<p>Nun werden wir unserem Kruzifix nicht gerecht, wenn wir es lediglich als das Instrument der Stifter betrachten, ihr Seelenheil zu sichern, und natürlich auch nicht, wenn wir es im Sinne Luthers als ein bloßes „Merkbild“ betrachten. Die naturalistische Wiedergabe feinster anatomischer Details und die naturgetreue farbige Fassung der Christusfigur zeigen, dass die Skulptur aufmerksam betrachtet werden will. Der Tote am Kreuz, sein geneigter Kopf unter der schweren Dornenkrone , das von Leid gezeichnete Gesicht und die klaffende Wunde an der Brust sind Appelle, sie fordern von jeden einzelnen Gläubigen Einfühlung und Mitleiden ein. Gerade darin sahen die Bilderfeinde eine Gefahr. Bei Andreas von Karlstadt lesen wir dazu: <em>„Aus dem Bild des gekreuzigten Christus lernst Du nur das fleischliche Leiden Christi, wie Christus sein Haupt geneigt und dergleichen. Nun sagt Christus, dass sein eigen Fleisch nichts nutz sei, sondern dass der Geist nutz sei und lebendig tut machen“.</em></p>
<p>Es greift aber natürlich auch zu kurz, unser Augenmerk einseitig auf die Naturtreue und das Pathos der Darstellung zu richten. Sie sind wichtige Aspekte eines Ganzen, das noch viel komplexer ist. Der Appell an das Einfühlungsvermögen entspricht einer persönlichen, subjektiven Frömmigkeit, den aufmerksam Betrachtenden werden aber dabei auch Widersprüche in der Gestaltung nicht verborgen bleiben. Wir wissen, dass die Skulptur einen toten Mann darstellt, der am Kreuze hängt; streng genommen sehen wir aber etwas anderes. So hängt kein toter Körper, Christus scheint vielmehr vor dem Kreuz fast zu schweben. Der Körper zeigt die Wunden, ist aber nicht geschunden und entstellt, und er ist nach der Vorstellung der Zeit von idealer Schönheit.<br>
Damit bezeugen die Künstler ihre Ehrfurcht vor der Gestalt Christi, die auch in der Erniedrigung ihre Würde und Schönheit nicht verlieren darf, sie bringen aber auch die Gewissheit zum Ausdruck, dass Christus den Tod überwindet, dass auf den Tod am Kreuz die Auferstehung folgen wird.</p>
<p>Diese Botschaft kommentieren und erweitern auch die Motive am Kreuz selbst. Die Symbole der vier Evangelisten an den Kreuzenden sind Hinweise auf die Evangelien als das Fundament des christlichen Glaubens, sie erinnern aber auch an die Verbreitung des Glaubens in alle vier Himmelsrichtungen, also in die ganze Welt.</p>
<p>Und die vergoldeten Blätter am Kreuz machen aus dem Hinrichtingsintrument einen Lebensbaum und verweisen auch sie auf das Thema der Auferstehung.</p>
</div>

## Johann Sebastian Bach: Die Johannes-Passion
### Einführungsvortrag 2020<br>KMD Volkmar Zehner, März 2020
<a href="/downloads/Vortrag_JoPa_Rotary-min.pdf" target="_blank">Klicken Sie hier um den Vortrag als PDF-Dokument herunterzuladen</a>

<?php $main = ob_get_clean();

require 'layouts/main.php';

